name: LimitedUses
version: ${project.version}
description: Genesis Addon - Allows to limit the amount of uses of items.
authors: [MageMonkeyStudio, Black_ixx]
website: https://magemonkey.studio
main: studio.magemonkey.genesis.addon.limiteduses.LimitedUses
depend: [Genesis]
commands:
  limiteduses:
   description: Allows editing the shopitem consume count of players
   aliases: [lius]
permissions:
  LimitedUses.Modify:
    description: Allows editing the shopitem consume count of players
    default: op